### ISSUE TITLE
add support for Amazon ECR as a chart repository

### ISSUE THREAD

**Issue by TarekAS** [jenkins-x/issues#29] opened 2021-02-02 09:51 UTC
Since [ECR now supports Helm Charts](https://aws.amazon.com/blogs/containers/oci-artifact-support-in-amazon-ecr/), it would be great to be able to use it as a chart repository in lieu of ChartMuseum.

Use case would be: it's cheaper for me to use ECR instead of running ChartMuseum

**Comment by jstrachan** [comment] 2021-02-16 15:26
we're just working through the various issues with moving to using `oci` for chart repositories. FWIW you can also use github pages which are effectively free for most folks and avoids running ChartMuseum. In your requirements file put...

```yaml
cluster: 
    chartRepository: https://github.com/my/chartrepo.git
    chartKind: pages
```

**Comment by msvticket** [comment] 2022-07-28 20:36
Duplicate of jenkins-x/jx#8285

**Closed by msvticket** 2022-07-28 20:36 UTC
